begin;
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','camobi','voluntários da pátria', '2322',null,'-29.708641','-53.723055');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','centro','rua A', '3453',null,'-29.694080','-53.774703');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','patronato','Av. Walter Jobim', '454',null,'-29.700368','-53.840743');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','centro','Av. Borges de Medeiros', '3453',null,'-29.687195','-53.822006');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','centro','Rua Duque de Caxias', '321',null,'-29.705774','-53.821495');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','KM3','Av. Osvaldo Cruz', '122',null,'-29.690546,','-53.785885');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','urlândia','Rua C', '11',null,'-29.719494','-53.808029');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','itararé','Av. dos Ferroviários', '243',null,'-29.676581','-53.808534');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Passo Dareia','R. Venâncio Aires', '2525',null,'-29.688950','-53.829175');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','T. Neves','Av. Paulo Lauda', '3632',null,'-29.694540','-53.874680');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Boca do Monte','Rua A', '4244',null,'-29.679518','-53.916124');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('Nova palma','RS','Centro','R. Siqueira Couto', '4444',null,'-29.473405','-53.473253');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Boi morto','Estr. Cap. Vasco Amaro da Cunha', '3632',null,'-29.714224','-53.850289');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('Porto alegre','RS','Partenon','Av. Ipiranga', '44543',null,'-30.056042','-51.161618');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('Porto alegre','RS','T. Neves','R. Voluntários da Pátria', '3632',null,'-30.026666','-51.222329');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('Caxias do Sul','RS','Centro','Av. São leopoldo', '34533',null,'-29.180839', '-51.185293');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Centro','Tuiuti', '3632',null,'-29.689092', '-53.806145');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Centro','Av. Borges de medeiros', '3632',null,'-29.691749', '-53.820531');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('pelotas','RS','Centro','Av. Bento gonçalves', '33545',null,'-31.760673', '-52.340839');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('bagé','RS','Centro','rua c', '3632',null,'-31.333005', '-54.104830');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Lorenzi','rua g', '3632',null,'-29.724385', '-53.806183');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Camobi','Av. carlos gomes', '777',null,'-29.698182', '-53.728071');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','JK','rua j', '5444',null,'-29.687353', '-53.859021');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','pains','estrada s', '3632',null,'-29.710629', '-53.763621');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','itararé','floriano peixoto', '3632',null,'-29.677789', '-53.809360');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Dores','euclides da cunha', '3632',null,'-29.686989', '-53.792585');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Av. Roraima','camobi', '111',null,'-29.702933', '-53.715476');
    insert into endereco(cidade,uf,bairro,rua,numero,complemento,latitude,longitude) values('santa maria','RS','Centro','Av. Presidente Vargas', '78966',null,'-29.695644', '-53.815124');
    insert into empresa(nome,razaosocial,endereco_id) values('empresa 1','empresa 1',1);
    insert into empresa(nome,razaosocial,endereco_id) values('empresa 2','empresa 2',2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 1','estab 1','08:00 ás 17:00',11,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 2','estab 2','10:00 ás 17:00',12,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 3','estab 3','07:00 ás 20:30',13,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 4','estab 4','09:00 ás 22:30',14,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 5','estab 5','06:00 ás 23:00',15,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 6','estab 6','08:00 ás 23:30',16,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 7','estab 7','12:00 ás 22:00',17,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 8','estab 8','09:00 ás 22:00',18,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 9','estab 9','09:00 ás 22:00',19,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 10','estab 10','06:00 ás 18:00',20,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 11','estab 11','07:00 ás 20:00',21,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 12','estab 12','09:00 ás 22:00',22,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 13','estab 13','11:00 ás 21:00',23,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 14','estab 14','18:00 ás 00:00',24,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 15','estab 15','08:00 ás 21:00',25,2);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 16','estab 16','13:00 ás 18:00',26,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 17','estab 17','14:00 ás 22:00',27,1);
    insert into estabelecimento(nome,razaosocial,horario_funcionamento,endereco_id,empresa_id) values('estab 18','estab 18','12:00 ás 14:00',28,2);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('joão','joao@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"CLIENTE"}',5);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm empresa 1','adm-emp-1@empresa1.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_EMPRESA"}',6);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 1','adm-estab-1@estab1.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',7);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('jonas','jonas@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"CLIENTE"}',8);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm empresa 2','adm-emp-2@empresa2.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_EMPRESA"}',9);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 2','adm-estab-2@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',10);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm sistema','adm@admgeral.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_SISTEMA"}',null); 
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 3','adm-estab-3@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 4','adm-estab-4@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 5','adm-estab-5@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 6','adm-estab-6@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 7','adm-estab-7@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 8','adm-estab-8@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 9','adm-estab-9@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 10','adm-estab-10@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 11','adm-estab-11@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 12','adm-estab-12@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 13','adm-estab-13@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 14','adm-estab-14@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 15','adm-estab-15@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 16','adm-estab-16@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 17','adm-estab-17@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);
    insert into usuario(nome,email,senha,permissoes,endereco_id) values('adm estab 18','adm-estab-18@gmail.com','$2a$11$NN91Lz01NlKX5XFfJ186PO6q21lZN0bp8ZyljHENUFjhB5z5b8mXa','{"ADMIN_ESTABELECIMENTO"}',null);  
    insert into cliente(id) values(1);
    insert into cliente(id) values(4);
    insert into adm_empresa(id,empresa_id) values(2,1);
    insert into adm_empresa(id,empresa_id) values(5,2);
    insert into adm_estabelecimento(id,estabelecimento_id) values(3,1);
    insert into adm_estabelecimento(id,estabelecimento_id) values(6,2);
    insert into adm_estabelecimento(id,estabelecimento_id) values(8,3);
    insert into adm_estabelecimento(id,estabelecimento_id) values(9,4);
    insert into adm_estabelecimento(id,estabelecimento_id) values(10,5);
    insert into adm_estabelecimento(id,estabelecimento_id) values(11,6);
    insert into adm_estabelecimento(id,estabelecimento_id) values(12,7);
    insert into adm_estabelecimento(id,estabelecimento_id) values(13,8);
    insert into adm_estabelecimento(id,estabelecimento_id) values(14,9);
    insert into adm_estabelecimento(id,estabelecimento_id) values(15,10);
    insert into adm_estabelecimento(id,estabelecimento_id) values(16,11);
    insert into adm_estabelecimento(id,estabelecimento_id) values(17,12);
    insert into adm_estabelecimento(id,estabelecimento_id) values(18,13);
    insert into adm_estabelecimento(id,estabelecimento_id) values(19,14);
    insert into adm_estabelecimento(id,estabelecimento_id) values(20,15);
    insert into adm_estabelecimento(id,estabelecimento_id) values(21,16);
    insert into adm_estabelecimento(id,estabelecimento_id) values(22,17);
    insert into adm_estabelecimento(id,estabelecimento_id) values(23,18);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 1','PENDENTE',1,1);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 2','PENDENTE',1,4);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 3','PENDENTE',2,1);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 4','PENDENTE',2,1);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 5','PENDENTE',2,4);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 6','PENDENTE',1,1);
    insert into pedido(descricao,status_pedido,estabelecimento_id,cliente_id) values('pedido 7','PENDENTE',2,4);
commit;