version: '3'
# docker-compose -p "avaliarprojetos" up -d
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - rede
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pooweb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    expose:
      - 8081
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pooweb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rede

networks:
  rede:
    driver: bridge
